### ISSUE TITLE
Dress Rehearsal

### ISSUE THREAD

**Issue by Frogpants** [KinetekEnergy/ByteBuffoons-Pages#27]
USAGE OF:

- [x]  Frontend
- [x]  Backend
- [x]  API
- [x]  Agile

HOOK:
Points: 3.8
Reason: The hook was interesting but turned into excuses for why some things were that way.

KNOWLEDGE:
Points: 4.0
Reason: Very knowledgeable about the code and how the program works.

VALUE:
Points: 0.85
Reason: The game has the potential to be great but lacks a few features.

WOW FACTOR:
Reason: It wasn't much, just a guy running back and forth with no sound.

**Comment by KinetekEnergy** [comment]
Wrong project.
